# Importing NumPy

In [ ]:
import numpy as np

Methods to create array

In [ ]:
arr = np.array([12,24,78,90,100.78])
arr

array([ 12.  ,  24.  ,  78.  ,  90.  , 100.78])

In [ ]:
lst = [29,79,34,1234,325]
arr = np.array(lst)
arr

array([  29,   79,   34, 1234,  325])

Array indexing same as list [start:end:step]

In [ ]:
arr[1]

79

To check shape of array

In [ ]:
arr.shape

(5,)

2D array

In [ ]:
lst = [[1,2,3,4],[5,6,7,8]]

arr_2d = np.array(lst)
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8]])
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr_2d.shape

(2, 4)

In [ ]:
arr_2d.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

# Indexing and Slicing


In [ ]:
lst = [[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]]


arr = np.array(lst)
arr

array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [ ]:
# arr[1::2,1:3]

# arr[0:3,1::3]

arr[::2,-1]

array([25, 37, 49])

Views in Array

In [ ]:
arr

array([[20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37],
       [38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49]])

In [ ]:
sub_arr = arr[1:5,1:5].copy()

In [ ]:
sub_arr[1,2] = 5000

In [ ]:
sub_arr

array([[  27,   28,   29,   30],
       [  33,   34, 5000,   36],
       [  39,   40,   41,   42],
       [  45,   46,   47,   48]])

Array Operations

In [ ]:
mini_arr1 = np.array([2,3,4,5,6,7])
mini_arr2 = np.array([7,6,5,4,3,2])


[ 4  9 16 25 36 49]


array([49, 36, 25, 16,  9,  4])

In [ ]:
mini_arr1 * 2
mini_arr1**3
mini_arr1/2

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [ ]:
mini_arr1 - mini_arr2

array([-5, -3, -1,  1,  3,  5])

# Array Mehtods

In [ ]:
np.zeros(10,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr = np.ones(10,dtype='int')
arr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.eye(5,dtype='int')

# or

# np.identity(10)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [ ]:
np.diag([2,4,6,8,10])

array([[ 2,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  6,  0,  0],
       [ 0,  0,  0,  8,  0],
       [ 0,  0,  0,  0, 10]])

In [ ]:
np.arange(1,11,2)
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.arange(1,11)
arr.reshape((2,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.random.rand(4)

array([0.37409821, 0.93089181, 0.12420082, 0.92008863])

In [ ]:
np.random.randn(6)

array([-5.78146539e-04,  9.21025499e-01,  1.35042784e+00, -5.10928292e-03,
       -2.45703507e-02,  2.84543176e-01])

In [ ]:
np.random.randint(20,50,20)

array([37, 20, 42, 36, 41, 26, 24, 29, 33, 24, 27, 34, 49, 29, 33, 38, 31,
       32, 30, 39])

In [ ]:
arr = np.random.randint(20,50,20)

In [ ]:
arr_2d = np.random.randint(20,50,20).reshape((5,4))
arr_2d

array([[39, 46, 31, 34],
       [35, 37, 28, 23],
       [25, 22, 35, 44],
       [24, 49, 43, 34],
       [26, 31, 32, 27]])

In [ ]:
arr_2d.min(axis=1)

array([31, 23, 22, 24, 26])

In [ ]:
arr_2d.max()

49

In [ ]:
arr_2d.argmin()

9

In [ ]:
arr_2d.argmax()

13

In [ ]:
arr.sum()

779

In [ ]:
arr.mean()

38.95

In [ ]:
np.median(arr)

41.0

In [ ]:
arr_2d.sum(axis=1)

array([150, 123, 126, 150, 116])

In [ ]:
arr_2d.mean(axis=0)

array([29.8, 37. , 33.8, 32.4])

In [ ]:
np.sqrt(arr)

array([6.08276253, 4.89897949, 5.74456265, 6.8556546 , 6.244998  ,
       5.83095189, 6.55743852, 6.78232998, 6.92820323, 5.19615242,
       5.56776436, 6.70820393, 5.83095189, 4.79583152, 6.92820323,
       6.08276253, 6.70820393, 6.8556546 , 6.70820393, 6.78232998])

In [ ]:
np.std(arr)

8.046583125774568

In [ ]:
arr.astype('float')

array([37., 24., 33., 47., 39., 34., 43., 46., 48., 27., 31., 45., 34.,
       23., 48., 37., 45., 47., 45., 46.])

github.com/sukhioo7/test